theme: jekyll-theme-minimal
title: Technicat LLC
url: http://technicat.com/
description: software development and consulting in very sunny Las Vegas
show_downloads: false
logo: /images/dakotasnow/CatGraphic300x300.jpg
appstore: https://apps.apple.com/us/developer/technicat-llc/id295241742
steam: https://store.steampowered.com/app/847530/HyperBowl/
