theme: jekyll-theme-minimal
title: Résumé
url: http://technicat.com/
description: résumé built with JSON and Scheme
show_downloads: true
logo: /images/icons/cat/catglasses.svg
domain: philipchu.com
copyright: Technicat LLC
