name: Copy markdown resume to other branch

on: [push]

jobs:
  copy:
    name: Copy my folder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy
        env:
          SRC_FILE: 'index.md'
          TARGET_BRANCH: 'gh-pages'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch                         # fetch branches
          git checkout $TARGET_BRANCH       # checkout to your branch
          git checkout ${GITHUB_REF##*/} -- $SRC_FILE # copy file from the source branch
          git add -A
          git diff-index --quiet HEAD ||  git commit -am "copy markdown"  # commit to the repository (ignore if no modification)
          git push origin $TARGET_BRANCH # push to remote branch
